- name: Deploying web app
  hosts: db-web
  tasks:
    - name: Ping
      ping:
    - name: Install web application packages
      yum: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip

    - name: Install mysql packages
      yum: name={{ item }} state=installed
      with_items:
        - mysql-server
        - mysql-client

    - name: Start mysql services
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create a application database
      mysql_db: name=employee_db state=present

    - name: Create a db user
      mysql_user:
        name: db_user
        password: root123
        priv: '*.*:ALL'
        state: present
    - name: Install Python Flask Dependency
      pip: name={{ item }} state=installed
      with_items:
        - flask
        - flask-mysql
    - name:
      copy: src=simple-webapp/app.py dest=/opt/app.py
    - name: Start Web Server
      shell: FLASK_APP-app.py nohup flask run --host=0.0.0.0 &



